#!/usr/bin/env bash
# Decision-differential harness: runs two revisions of hooks/guard-bash.sh over a corpus and
# prints every input where their allow/deny decisions differ.
#
# Usage:
#   tests/tools/diff-decisions.sh <hook-A> <hook-B> [corpus-file]
#
# With no corpus file, one is generated by tests/tools/gen-corpus.sh (every command string the
# existing guard-bash suites exercise, plus a generated cross-product — see that file's header).
# The corpus is NUL-delimited, not newline-delimited (see gen-corpus.sh's header for why); a
# corpus-file argument must use the same format.
#
# `just diff-decisions <baseline-git-revision>` runs this against a git revision's copy of
# hooks/guard-bash.sh vs. the current working tree — see the justfile. That recipe is NOT part
# of `ci`; this is machinery for a human to invoke explicitly before landing a change to
# hooks/guard-bash.sh, never a default-path gate.
#
# GATE FOR FUTURE ROUNDS ON THIS FILE: before landing any change to hooks/guard-bash.sh, run
#
#   just diff-decisions <parent-commit>
#
# and confirm every printed line is an intended flip already documented in that round's spec.
# An undocumented flip is a regression — stop and investigate before landing, never explain it
# away after the fact. The invariant that matters is DECISIONS, proven at runtime over a
# corpus, not bytes proven statically over a diff.
#
# TWO POSITIVE CONTROLS guard against this harness going green having compared nothing:
# - MIN_CORPUS: the corpus must contain at least this many records. Without this, a
#   corpus-generation failure (gen-corpus.sh's own mktemp guard exiting non-zero with empty
#   stdout, or a future refactor that silently drops the cross-product) produces an empty
#   corpus, the comparison loop never runs, and the script would otherwise print
#   "0 inputs compared, 0 differ" and exit 0 — a vacuous pass. gen-corpus.sh's real output is
#   ~240 records; MIN_CORPUS is set well below that so healthy runs always clear it.
# - MIN_DENIES: revision B must deny at least this many corpus lines. This guards a second,
#   independent false-green path: if both revisions fail IDENTICALLY (e.g. jq is unavailable,
#   so every hook_decision call returns "allow" by construction) the diff count is also zero.
#   A harness that cannot demonstrate it observed any deny from B is not measuring anything.
# - CONTROL_CMD: BOTH revisions must deny one fixed input that every healthy revision of this
#   guard denies, checked before the corpus loop runs. MIN_DENIES only ever looked at B, so a
#   revision A that was not running at all went completely unnoticed — and that is not
#   hypothetical: `just diff-decisions` used to materialize the baseline as a lone temp file,
#   whose runtime `hooks/lib/*.sh` source then failed, so the baseline took its degraded
#   fail-open branch and ALLOWED EVERY INPUT. Every corpus deny from B then reads as a "flip",
#   which looks like a rich, informative diff instead of an obvious failure. Comparing against a
#   guard that is switched off is worse than not comparing: it manufactures evidence.
set -uo pipefail

DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091 # resolved relative to this file at runtime
. "$DIR/../lib/hookcase.sh"

MIN_CORPUS=150
MIN_DENIES=100
# An unleased force-push: denied by the pre-branch baseline and by every revision since, so a
# revision that ALLOWS it is not running rather than merely disagreeing. See the header note.
CONTROL_CMD="g""it push --force origin main"

usage() {
  echo "usage: $0 <hook-A> <hook-B> [corpus-file]" >&2
  exit 2
}

[ "$#" -ge 2 ] || usage
HOOK_A="$1"
HOOK_B="$2"
CORPUS_FILE="${3-}"

[ -f "$HOOK_A" ] || {
  echo "diff-decisions: hook-A not found: $HOOK_A" >&2
  exit 2
}
[ -f "$HOOK_B" ] || {
  echo "diff-decisions: hook-B not found: $HOOK_B" >&2
  exit 2
}

# Positive control 3: both revisions must be RUNNING, proven before any comparison happens.
control_a="$(hook_decision "$HOOK_A" "$CONTROL_CMD")"
control_b="$(hook_decision "$HOOK_B" "$CONTROL_CMD")"
if [ "$control_a" != "deny" ] || [ "$control_b" != "deny" ]; then
  echo "diff-decisions: control input was not denied by both revisions (A=$control_a, B=$control_b). Every healthy revision of this guard denies it, so a revision that allows it is NOT RUNNING — most likely materialized outside hooks/, where its runtime 'lib/*.sh' source fails and it takes the degraded fail-open branch that allows everything. Refusing to compare against a guard that is switched off." >&2
  exit 2
fi

TMP_CORPUS=""
if [ -z "$CORPUS_FILE" ]; then
  TMP_CORPUS="$(mktemp 2>/dev/null)" || {
    echo "diff-decisions: mktemp failed" >&2
    exit 2
  }
  trap 'rm -f "$TMP_CORPUS"' EXIT
  if ! bash "$DIR/gen-corpus.sh" >"$TMP_CORPUS"; then
    echo "diff-decisions: gen-corpus.sh exited non-zero — corpus generation failed, refusing to run a comparison against a possibly-empty or partial corpus" >&2
    exit 2
  fi
  CORPUS_FILE="$TMP_CORPUS"
fi
[ -f "$CORPUS_FILE" ] || {
  echo "diff-decisions: corpus file not found: $CORPUS_FILE" >&2
  exit 2
}

# Positive control 1: refuse a suspiciously small (or empty) corpus outright, before running a
# single comparison — see the MIN_CORPUS note in the header above.
records="$(tr -cd '\0' <"$CORPUS_FILE" | wc -c | tr -d '[:space:]')"
if [ "$records" -lt "$MIN_CORPUS" ]; then
  echo "diff-decisions: corpus has only $records record(s), floor is $MIN_CORPUS — refusing to run a comparison this thin. Either gen-corpus.sh failed to produce its normal output, or a non-default corpus-file argument is genuinely too small; raise MIN_CORPUS in this script if the latter is intentional." >&2
  exit 2
fi

total=0
diffs=0
b_denies=0
while IFS= read -r -d '' cmd; do
  [ -z "$cmd" ] && continue
  total=$((total + 1))
  a="$(hook_decision "$HOOK_A" "$cmd")"
  b="$(hook_decision "$HOOK_B" "$cmd")"
  [ "$b" = "deny" ] && b_denies=$((b_denies + 1))
  if [ "$a" != "$b" ]; then
    diffs=$((diffs + 1))
    printf 'DIFF  A=%-9s B=%-9s  %s\n' "$a" "$b" "$cmd"
  fi
done <"$CORPUS_FILE"

printf '\n%d inputs compared, %d differ, %d denied by B\n' "$total" "$diffs" "$b_denies"

# Positive control 2: revision B must have actually denied something — see the MIN_DENIES note
# in the header above. Checked AFTER the loop (so the DIFF lines and the summary above are
# still printed for debugging) but before the final pass/fail exit.
if [ "$b_denies" -lt "$MIN_DENIES" ]; then
  echo "diff-decisions: revision B (\"$HOOK_B\") denied only $b_denies of $total inputs, floor is $MIN_DENIES — a harness that observed no meaningful deny rate from B is not measuring anything (both revisions may be failing identically, e.g. jq unavailable so every call returns \"allow\")." >&2
  exit 2
fi

[ "$diffs" -eq 0 ]
