#!/usr/bin/env bash
# gen-skill-catalog — generate a machine index of every skill from its SKILL.md frontmatter, bucketed
# by domain (derived from the standards/<domain>/ doc it points at). Deterministic: repeated runs
# produce byte-identical output, so CI can regenerate and diff to catch a stale catalog.
#   usage: ./scripts/gen-skill-catalog.sh           # prints to stdout
#          ./scripts/gen-skill-catalog.sh > skills/CATALOG.md
# Pure bash + awk/grep. `set -euo pipefail`: abort on error (a generator must not emit partial output).
# See standards/languages/shell.md.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 2

field() { # $1=file $2=key  → frontmatter value (top-level or nested)
  awk -v k="$2" '/^---[[:space:]]*$/{d++; next} d==1 && $0 ~ ("^[[:space:]]*" k ":") {sub("^[[:space:]]*" k ":[[:space:]]*",""); print; exit}' "$1"
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

for f in skills/*/SKILL.md; do
  [ -e "$f" ] || continue
  name="$(field "$f" name)"
  desc="$(field "$f" description)"
  ver="$(field "$f" version)"
  # primary domain = the domain of the first standards/<domain>/ doc the skill references; meta if none
  domain="$(grep -oE 'standards/[a-z-]+/' "$f" | head -1 | sed -E 's|standards/||; s|/||')"
  [ -n "$domain" ] || domain="meta"
  printf '%s\t%s\t%s\t%s\t%s\n' "$domain" "$name" "$ver" "$f" "$desc" >>"$tmp"
done

count="$(wc -l <"$tmp" | tr -d ' ')"
printf '<!-- generated by scripts/gen-skill-catalog.sh — do not edit by hand -->\n'
printf '# Skills Catalog\n\n'
# shellcheck disable=SC2016  # backticks are literal Markdown code spans; the format string must stay single-quoted
printf 'Auto-generated index of all %s skills. Refresh with `bash scripts/gen-skill-catalog.sh > skills/CATALOG.md`.\n' "$count"

for domain in meta languages frameworks platform practices design; do
  rows="$(LC_ALL=C sort -t'	' -k2,2 "$tmp" | awk -F'\t' -v d="$domain" '$1==d')"
  [ -n "$rows" ] || continue
  printf '\n## %s\n\n' "$domain"
  printf '%s\n' "$rows" | while IFS=$'\t' read -r _ name ver path desc; do
    # shellcheck disable=SC2016  # backticks are literal Markdown code spans, not command substitution
    printf -- '- **[%s](%s)** `v%s` — %s\n' "$name" "${path#skills/}" "$ver" "$desc"
  done
done
